# ---------------------------------------------------------
# shared/docker-compose.yml
# Shared Infrastructure: Redis + Nginx + Let's Encrypt
# ---------------------------------------------------------

name: shared-infrastructure

services:
  # Shared Redis Cache (aman untuk di-share karena stateless)
  shared-redis:
    image: redis:7-alpine
    container_name: shared-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - shared-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 10

  # Shared Nginx Reverse Proxy dengan Let's Encrypt
  shared-nginx:
    image: nginx:alpine
    container_name: shared-nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites:/etc/nginx/sites-enabled:ro
      - ./certbot:/var/www/certbot
      - ./letsencrypt:/etc/letsencrypt
      - nginx_logs:/var/log/nginx
    networks:
      - shared-network
    healthcheck:
      test: ["CMD-SHELL", "nginx -t || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

  # Certbot untuk Let's Encrypt SSL certificates
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot:/var/www/certbot
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - shared-network
    # Tidak auto start; dipanggil via make commands
    restart: "no"

volumes:
  redis_data:
  nginx_logs:

networks:
  shared-network:
    external: true
